# $ docker compose --env-file=container.env up -d
---
networks:
  federated-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
volumes:
  cv-iris-data:
  cv-hs-data:
  ucr-iris-data:
  ucr-hs-data:
services:
  webgateway:
    image: containers.intersystems.com/intersystems/webgateway:latest-cd
    init: true
    hostname: ${PROJECT_NAME}
    container_name: ${PROJECT_NAME}-web-gateway
    ports:
      - 80:80
      # - 443:443 # ssl
    # command: --ssl # ssl
    volumes:
      - ./web-gateway/CSP.ini:/opt/webgateway/bin/CSP.ini
      - ./web-gateway/CSP.conf:/etc/apache2/mods-available/CSP.conf
      - ./web-gateway/apache2.conf:/etc/apache2/apache2.conf
      # - ./web-gateway/certificate/ssl-cert.key:/irissys/tls/webgateway/tls.key # ssl
      # - ./web-gateway/certificate/ssl-cert.pem:/irissys/tls/webgateway/tls.crt # ssl
    networks:
      federated-network:
        ipv4_address: 192.168.10.10
  cv-instance:
    image: containers.intersystems.com/intersystems/healthshare_clinicalviewer:2024.2
    init: true
    hostname: ${PROJECT_NAME}-cv
    container_name: ${PROJECT_NAME}-cv
    command: --key /config/iris/iris.key
      --instance HSCV
      -c "sudo chown -R 51773:51773 /data/iris/ && sudo chown -R 51773:51773 /data/hs/"
    environment:
      - ISC_DATA_DIRECTORY=/data/iris/
      - ISC_CPF_MERGE_FILE_NAME=merge.cpf
      - ISC_HS_DATA_DIRECTORY=/data/hs/
      - ISC_CONFIG_DIRECTORY=/config/iris/
      - ISC_CPF_MERGE_FILE=/config/iris/merge.cpf
      - ISC_HS_CONFIG_DIRECTORY=/config/hs/
      - ISC_HS_CONFIG_BASE_FILENAME=hs-base-config.json
      - ISC_HS_DATA_INGESTION_DIRECTORY=/data-ingestion/Data/
    volumes:
      - ./cv-config/iris/:/config/iris/
      - ./cv-config/hs/:/config/hs/
      - ./data-ingestion/Data/:/data-ingestion/Data/
      - cv-iris-data:/data/iris/
      - cv-hs-data:/data/hs/
    networks:
      federated-network:
        ipv4_address: 192.168.10.11
  ucr-instance:
    image: containers.intersystems.com/intersystems/healthshare_unifiedcarerecord_insight_patientindex:2024.2
    init: true
    hostname: ${PROJECT_NAME}-ucr
    container_name: ${PROJECT_NAME}-ucr
    command: --key /config/iris/iris.key
      --instance HSUCR
      -c "sudo chown -R 51773:51773 /data/iris/ && sudo chown -R 51773:51773 /data/hs/"
    environment:
      - ISC_DATA_DIRECTORY=/data/iris/
      - ISC_CPF_MERGE_FILE_NAME=merge.cpf
      - ISC_HS_DATA_DIRECTORY=/data/hs/
      - ISC_CONFIG_DIRECTORY=/config/iris/
      - ISC_CPF_MERGE_FILE=/config/iris/merge.cpf
      - ISC_HS_CONFIG_DIRECTORY=/config/hs/
      - ISC_HS_CONFIG_BASE_FILENAME=hs-base-config.json
      - ISC_HS_DATA_INGESTION_DIRECTORY=/data-ingestion/Data/
    volumes:
      - ./ucr-config/iris/:/config/iris/
      - ./ucr-config/hs/:/config/hs/
      - ./data-ingestion/Data/:/data-ingestion/Data/
      - ucr-iris-data:/data/iris/
      - ucr-hs-data:/data/hs/
    networks:
      federated-network:
        ipv4_address: 192.168.10.12
